export const ProductTypes = {
  START_FETCHING_PRODUCTS: "START_FETCHING_PRODUCTS",
  FETCHING_PRODUCTS_SUCCESS: "FETCHING_PRODUCTS_SUCCESS",
  FETCH_PRODUCT_BY_ID: 'FETCH_PRODUCT_BY_ID',
  SET_PRODUCTS: "SET_PRODUCTS",
  CREATE_PRODUCT: "CREATE_PRODUCT",
  START_PRODUCT_UPDATE: "START_PRODUCT_UPDATE",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  SET_CATEGORY: "SET_CATEGORY",
  SET_MIN_PRICE: "SET_MIN_PRICE",
  SET_MAX_PRICE: "SET_MAX_PRICE",
  SET_KEYWORD: "SET_KEYWORD",
};
