//User actions
export const SET_USER_DATA = "SET_USER_DATA";
export const FETCH_USER_ERROR = "FETCH_USER_ERROR";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";
export const STARTED_SIGN_IN = "STARTED_SIGN_IN";

// Products actions
export const START_FETCHING_PRODUCTS = "START_FETCHING_PRODUCTS";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const FETCHING_PRODUCTS_SUCCESS = "FETCHING_PRODUCTS_SUCCESS";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const START_PRODUCT_UPDATE = "START_PRODUCT_UPDATE";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const SET_CATEGORY = "SET_CATEGORY";
export const SET_MIN_PRICE = "SET_MIN_PRICE";
export const SET_MAX_PRICE = "SET_MAX_PRICE";
export const SET_KEYWORD = "SET_KEYWORD";

// Cart actions
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const INCREASE_ITEM_AMOUNT = "INCREASE_ITEM_AMOUNT";
export const DECREASE_ITEM_AMOUNT = "DECREASE_ITEM_AMOUNT";
export const RESET_CART = "RESET_CART";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const CALCULATE_TOTAL = "CALCULATE_TOTAL";
