//User actions
export const SET_USER_DATA = "SET_USER_DATA";
export const FETCH_USER_ERROR = "FETCH_USER_ERROR";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";

// Products actions
export const START_FETCHING_PRODUCTS = "START_FETCHING_PRODUCTS";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const FETCHING_PRODUCTS_SUCCESS = "FETCHING_PRODUCTS_SUCCESS";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const START_PRODUCT_UPDATE = "START_PRODUCT_UPDATE";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
